# Generated by Django 3.1.2 on 2021-04-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID альбома')),
                ('album_name', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('album_desc', models.CharField(max_length=1000, verbose_name='Описание альбома')),
                ('album_release_date', models.DateField(verbose_name='Дата выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('artist_start_career_date', models.DateField(verbose_name='Дата старта карьеры')),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('genre_description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('composition_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID композиции')),
                ('composition_title', models.CharField(max_length=50, verbose_name='Название композиции')),
                ('composition_duration', models.TimeField(verbose_name='Длительность')),
                ('composition_text', models.CharField(max_length=1000, verbose_name='Название композиции')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.album', verbose_name='ID альбома')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.musicgenre', verbose_name='ID жанра')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.artist', verbose_name='ID артиста'),
        ),
    ]
