# Generated by Django 3.1.2 on 2021-04-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Композиция', 'verbose_name_plural': 'Композиции'},
        ),
        migrations.AlterModelOptions(
            name='musicgenre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID альбома'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composition_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID композиции'),
        ),
        migrations.AlterField(
            model_name='musicgenre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
